name: Unzip ZIP File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: unzip "Rchat All Screens.zip" -d .

      - name: Remove ZIP
        run: rm -f "Rchat All Screens.zip"

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzip project files" || exit 0
          git push
