name: Unzip ZIP File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip File
        run: |
          unzip "Rchat All Screens.zip" -d .

      - name: Delete ZIP (Optional)
        run: rm -f "Rchat All Screens.zip"

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Unzip project files" || echo "No changes"

          git push origin main
